# Generated by Django 4.2.6 on 2023-10-21 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игру', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='games',
            name='system_requirements',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Системные требования:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='games',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
