# Generated by Django 4.2.6 on 2023-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0002_alter_category_options_alter_games_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='download',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
