# Generated by Django 4.2.6 on 2023-11-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0006_rename_created_add_games_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='update_at',
        ),
        migrations.AddField(
            model_name='games',
            name='changes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Изменение'),
        ),
        migrations.AddField(
            model_name='games',
            name='developer',
            field=models.CharField(max_length=100, null=True, verbose_name='Разработчик'),
        ),
        migrations.AddField(
            model_name='games',
            name='genre_game',
            field=models.CharField(max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='games',
            name='interface_language',
            field=models.CharField(max_length=100, null=True, verbose_name='Язык интерфейса'),
        ),
        migrations.AddField(
            model_name='games',
            name='platform',
            field=models.CharField(max_length=100, null=True, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='games',
            name='publisher',
            field=models.CharField(max_length=100, null=True, verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='games',
            name='release_date_game',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AddField(
            model_name='games',
            name='repack',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип издания'),
        ),
        migrations.AddField(
            model_name='games',
            name='tablet',
            field=models.CharField(max_length=100, null=True, verbose_name='Таблeтка'),
        ),
        migrations.AddField(
            model_name='games',
            name='voice_over_language',
            field=models.CharField(max_length=100, null=True, verbose_name='Язык озвучки'),
        ),
        migrations.AlterField(
            model_name='games',
            name='photo',
            field=models.ImageField(upload_to='photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='games',
            name='uploads',
            field=models.IntegerField(default=0, null=True, verbose_name='Скачали: '),
        ),
    ]
