# Generated by Django 4.2.6 on 2023-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0007_remove_games_update_at_games_changes_games_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to='Downloads/', verbose_name='Файл для скачивания'),
        ),
    ]
