# Generated by Django 4.2.6 on 2023-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0008_alter_games_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка видео'),
        ),
    ]
