# Generated by Django 4.2.6 on 2023-11-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0009_games_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='repack_and_repack_size',
            field=models.CharField(max_length=100, null=True, verbose_name='Репак и размер репака'),
        ),
    ]
