# Generated by Django 4.2.6 on 2023-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='О себе'),
        ),
    ]
