# Generated by Django 4.2.6 on 2023-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0013_profile_address_alter_profile_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='video',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка видео'),
        ),
    ]
