# Generated by Django 4.2.6 on 2023-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0014_alter_games_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='repack_and_repack_size',
            field=models.CharField(max_length=100, null=True, verbose_name='Размер игры или Репак и размер репака'),
        ),
    ]
