# Generated by Django 4.2.6 on 2023-12-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_games', '0015_alter_games_repack_and_repack_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игр')),
                ('context', models.TextField(verbose_name='Описание игры')),
                ('system_requirements', models.TextField(verbose_name='Системные требования:')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Изменение')),
                ('release_date_game', models.CharField(max_length=100, null=True, verbose_name='Дата выхода')),
                ('genre_game', models.CharField(max_length=100, null=True, verbose_name='Жанр')),
                ('developer', models.CharField(max_length=100, null=True, verbose_name='Разработчик')),
                ('publisher', models.CharField(max_length=100, null=True, verbose_name='Издательство')),
                ('platform', models.CharField(max_length=100, null=True, verbose_name='Платформа')),
                ('repack', models.CharField(max_length=100, null=True, verbose_name='Тип издания')),
                ('interface_language', models.CharField(max_length=100, null=True, verbose_name='Язык интерфейса')),
                ('voice_over_language', models.CharField(max_length=100, null=True, verbose_name='Язык озвучки')),
                ('tablet', models.CharField(max_length=100, null=True, verbose_name='Таблeтка')),
                ('video', models.CharField(max_length=255, null=True, verbose_name='Ссылка видео')),
                ('uploads', models.IntegerField(default=0, null=True, verbose_name='Скачали: ')),
                ('repack_and_repack_size', models.CharField(max_length=100, null=True, verbose_name='Размер игры или Репак и размер репака')),
                ('download', models.FileField(blank=True, null=True, upload_to='Downloads/', verbose_name='Файл для скачивания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrent_games.category')),
            ],
            options={
                'verbose_name': 'Популярную игру',
                'verbose_name_plural': 'Популярные игры',
            },
        ),
    ]
